GET http://localhost:8080/dates?dates=2024-05-11,2024-05-12,2024-05-13
Content-Type: application/json



###
POST http://localhost:8080/dates
Content-Type: application/json

{
  "2024-04-11": [
    {
      "uuid": "c3165e32-4740-4b12-9a47-1e7b3a82276d",
      "name": "Test task",
      "completed": false
    }
  ]
}
