POST http://localhost:4000/login
Content-Type: application/json

{
  "username": "offz",
  "password": "password"
}


###
POST http://localhost:4000/dates
Content-Type: application/json

{
  "2024-05-11": [
    {
      "uuid": "c3165e32-4740-4b12-9a47-1e7b3a82276d",
      "name": "Test task",
      "completed": false
    }
  ]
}
